/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api.public.bootstrap-admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/': typeof AppIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/api/public/bootstrap-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/admin'
    | '/plan'
    | '/profile'
    | '/progress'
    | '/'
    | '/api/public/bootstrap-admin'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/_app/admin'
    | '/_app/plan'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/'
    | '/api/public/bootstrap-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
